2024-05-19 16:53:18,754 INFO    MainThread:83490 [wandb_setup.py:_flush():76] Current SDK version is 0.16.6
2024-05-19 16:53:18,754 INFO    MainThread:83490 [wandb_setup.py:_flush():76] Configure stats pid to 83490
2024-05-19 16:53:18,754 INFO    MainThread:83490 [wandb_setup.py:_flush():76] Loading settings from /Users/matteo/.config/wandb/settings
2024-05-19 16:53:18,754 INFO    MainThread:83490 [wandb_setup.py:_flush():76] Loading settings from /Users/matteo/Documents/MSc/Period5/DL2/Project/Confidently_Exiting/wandb/settings
2024-05-19 16:53:18,754 INFO    MainThread:83490 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-05-19 16:53:18,754 WARNING MainThread:83490 [wandb_setup.py:_flush():76] Could not find program at -m run_summarization
2024-05-19 16:53:18,754 INFO    MainThread:83490 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': None, 'program': '-m run_summarization'}
2024-05-19 16:53:18,754 INFO    MainThread:83490 [wandb_setup.py:_flush():76] Applying login settings: {}
2024-05-19 16:53:18,754 INFO    MainThread:83490 [wandb_setup.py:_flush():76] Applying login settings: {}
2024-05-19 16:53:18,754 INFO    MainThread:83490 [wandb_init.py:_log_setup():521] Logging user logs to /Users/matteo/Documents/MSc/Period5/DL2/Project/Confidently_Exiting/wandb/run-20240519_165318-ompekbaq/logs/debug.log
2024-05-19 16:53:18,754 INFO    MainThread:83490 [wandb_init.py:_log_setup():522] Logging internal logs to /Users/matteo/Documents/MSc/Period5/DL2/Project/Confidently_Exiting/wandb/run-20240519_165318-ompekbaq/logs/debug-internal.log
2024-05-19 16:53:18,754 INFO    MainThread:83490 [wandb_init.py:init():561] calling init triggers
2024-05-19 16:53:18,754 INFO    MainThread:83490 [wandb_init.py:init():568] wandb.init called with sweep_config: {}
config: {'dataset': 'samsum', 'model': 'jvelja/t5-samsum', 'exit_conf_type': 'reweight_contrastive_decoding', 'exit_conf_threshold': 0.9, 'exit_min_layer': 2}
2024-05-19 16:53:18,754 INFO    MainThread:83490 [wandb_init.py:init():611] starting backend
2024-05-19 16:53:18,754 INFO    MainThread:83490 [wandb_init.py:init():615] setting up manager
2024-05-19 16:53:18,757 INFO    MainThread:83490 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2024-05-19 16:53:18,758 INFO    MainThread:83490 [wandb_init.py:init():623] backend started and connected
2024-05-19 16:53:18,762 INFO    MainThread:83490 [wandb_init.py:init():715] updated telemetry
2024-05-19 16:53:18,780 INFO    MainThread:83490 [wandb_init.py:init():748] communicating run to backend with 90.0 second timeout
2024-05-19 16:53:19,171 INFO    MainThread:83490 [wandb_run.py:_on_init():2357] communicating current version
2024-05-19 16:53:19,251 INFO    MainThread:83490 [wandb_run.py:_on_init():2366] got version response upgrade_message: "wandb version 0.17.0 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2024-05-19 16:53:19,252 INFO    MainThread:83490 [wandb_init.py:init():799] starting run threads in backend
2024-05-19 16:53:20,932 WARNING MainThread:83490 [wandb_init.py:init():1203] interrupted
Traceback (most recent call last):
  File "/Users/matteo/anaconda3/envs/dl2/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1181, in init
    run = wi.init()
  File "/Users/matteo/anaconda3/envs/dl2/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 841, in init
    run._on_start()
  File "/Users/matteo/anaconda3/envs/dl2/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2389, in _on_start
    self._backend.interface.publish_python_packages(working_set())
  File "/Users/matteo/anaconda3/envs/dl2/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 295, in publish_python_packages
    for pkg in working_set:
  File "/Users/matteo/anaconda3/envs/dl2/lib/python3.10/site-packages/wandb/util.py", line 1878, in working_set
    yield InstalledDistribution(key=d.metadata["Name"], version=d.version)
  File "/Users/matteo/anaconda3/envs/dl2/lib/python3.10/importlib/metadata/__init__.py", line 612, in metadata
    return _adapters.Message(email.message_from_string(text))
  File "/Users/matteo/anaconda3/envs/dl2/lib/python3.10/email/__init__.py", line 38, in message_from_string
    return Parser(*args, **kws).parsestr(s)
  File "/Users/matteo/anaconda3/envs/dl2/lib/python3.10/email/parser.py", line 67, in parsestr
    return self.parse(StringIO(text), headersonly=headersonly)
  File "/Users/matteo/anaconda3/envs/dl2/lib/python3.10/email/parser.py", line 57, in parse
    return feedparser.close()
  File "/Users/matteo/anaconda3/envs/dl2/lib/python3.10/email/feedparser.py", line 187, in close
    self._call_parse()
  File "/Users/matteo/anaconda3/envs/dl2/lib/python3.10/email/feedparser.py", line 180, in _call_parse
    self._parse()
  File "/Users/matteo/anaconda3/envs/dl2/lib/python3.10/email/feedparser.py", line 469, in _parsegen
    self._cur.set_payload(EMPTYSTRING.join(lines))
KeyboardInterrupt
2024-05-19 16:53:23,111 WARNING MsgRouterThr:83490 [router.py:message_loop():77] message_loop has been closed
